### ISSUE TITLE
Build failure on MSYS

### ISSUE THREAD

**Issue by tjliupeng** [garyhouston/rxspencer#1]
Try to build it on MSYS. The failure is when calling make after configure, the error is: ltmain.sh: no such file or directory.

**Comment by garyhouston** [comment]
That file was a symlink when it should have been copied. I've fixed it in the repository. However I'm not sure if building shared libraries will work on that platform. If you don't need shared libraries, you can use the simpler regex repository at https://github.com/garyhouston/regex which has a simple Makefile.
